### ISSUE TITLE
Inconsistent snapshot directory for `cypress run` vs. `cypress open`

### ISSUE THREAD

**Issue by cangoektas** [palmerhq/cypress-image-snapshot#17]
Hi!

I found out that snapshots are saved in different directories depending on if they are created using `cypress run` or `cypress open`.

### Steps to reproduce
1. Delete the `examples/snapshot` directory
2. Run `cypress run`
3. Run `crypress open` and click on `Run all specs`

What happens is that the same call to `matchImageSnapshot` produces two different snapshot files:

![screen shot 2018-07-19 at 17 37 38](https://user-images.githubusercontent.com/1178516/42953350-8af0d596-8b7a-11e8-9feb-ac74b497d110.png)

I stumbled open this because I made a change and expected the tests to fail but since there was a new file created everything was still green. I would expect that the previous snapshot should have been used to match against the new screenshot.

Is there something we can do here?

**Comment by crosscompile** [comment]
I've noticed this behavior as well and it's not ideal.  I think it's caused by https://github.com/cypress-io/cypress/issues/2091 since we just mirror the `screenshots` directory in `snapshots`.

It looks like a fix for the issue is targeting Cypress `v3.0.3` though so hopefully that is released soon.

**Comment by crosscompile** [comment]
Just noticed that [`3.0.3` was released](https://docs.cypress.io/guides/references/changelog.html#3-0-3) and this issue was fixed 🎉.
