### ISSUE TITLE
cy.screenshot() timeout error while running cypress with `cypress-image-snapshot`

### ISSUE THREAD

**Issue by gokatz** [palmerhq/cypress-image-snapshot#25]
The package looks great and it helped in automating my testing process well. Thanks for this 🙂
I'm using this package with vuejs.

Few errors I encounter often are, 
* `CypressError: cy.screenshot() timed out waiting '30000ms' to complete.` while running cypress test with `cy.matchImageSnapshot('home')` even though if there is no diff in image. 
* Inconsistent screenshot folder (`<rootFolder>/screenshots`, `<rootFolder>/tests/e2e/screenshots`)
* Inconsistent file names (`home.snap.png`, `home-snap.png`)
* When there is a actual diff in output, cypress doesn't throw the specific error (Image mismatch). Instead, it throws the above said timeout error.

**Comment by crosscompile** [comment]
Thanks for reporting these issues!

Which version of Cypress are you using?  The behavior of the `screenshot` command has been changing recently so some of these bugs could depend on your Cypress version.

If possible I would recommend updating to the latest version of Cypress (currently 3.1.0) since they have also fixed some nasty bugs we were having on CI.

Otherwise `cypress-image-snapshot@>=1.0.0 <2.0.0` should work with `cypress@>=3.0.0 <3.0.2`
and `cypress-image-snapshot@>2.0.0` should work with `cypress@>3.0.2`.  I can document these ranges in the readme.

Let me know if none of that works and we can try to track down each bug.

**Comment by crosscompile** [comment]
Closing this for now, feel free to re-open if the issue still persists.

**Comment by shockey** [comment]
I had this issue as well, when using `capture: "fullPage"`. Raising the timeout for screenshots fixed it.

In `support/commands.js`:

```
addMatchImageSnapshotCommand({
  timeout: "60000"
})
```
